name: cleancity
description: "Projet CleanCity - Architecture 3-Tier avec BaaS Firebase"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
  # Gestion des médias et matériel (Couche Présentation)
  image_picker: ^1.2.1
  geolocator: ^11.1.0
  
  # Cartographie (Localisation temps réel)
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  
  # Services Firebase (Couche de Données BaaS)
  firebase_core: ^3.10.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0 # <--- CETTE LIGNE ÉTAIT MANQUANTE

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/home.jpg